---
- name: Install Artifactory
  hosts: artifactory_servers
  become: yes
  vars:
    artifactory_home: "/opt/artifactory"
    artifactory_port: 8081

  tasks:
    - name: Create Artifactory user and group
      group:
        name: artifactory
        state: present

    - name: Create Artifactory user
      user:
        name: artifactory
        group: artifactory
        home: "{{ artifactory_home }}"
        shell: /bin/bash
        state: present
    
    - name: Ensure required packages are installed
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - wget

    - name: Download Artifactory tarball
      get_url:
        url: "https://releases.jfrog.io/artifactory/artifactory-pro/org/artifactory/pro/jfrog-artifactory-pro/[RELEASE]/jfrog-artifactory-pro-[RELEASE]-linux.tar.gz?_gl=1*uqzsru*_ga*NDA3OTk5MzcwLjE3MTQ5MTAzOTc.*_ga_SQ1NR9VTFJ*MTcxNjkwOTU1My4yLjEuMTcxNjkwOTg3NS4wLjAuMTIxNzE1OTA4MQ..*_fplc*bEZ5enZDTmVTT1k3WVZwWUhBbyUyRlhucmFFMVBBOCUyQmpFdG1yODlqTERpc3M0ZlVjVzFtNUEyTU53aWtCbHJreWZyN1NudFlJbkZpejliQkE3VTN1NmtWSzkwZk43RjRubENLeEJOU0RtNHcyN3JlSm9iSG5CUmpaOSUyQllXUnlRJTNEJTNE"
        dest: /tmp/artifactory.tar.gz
        mode: '0644'

    - name: Extract Artifactory
      unarchive:
        src: /tmp/artifactory.tar.gz
        dest: "{{ artifactory_home }}"
        remote_src: yes
        creates: "{{ artifactory_home }}/artifactory"

    - name: Set symlink to Artifactory directory
      file:
        src: "{{ artifactory_home }}/artifactory"
        dest: "{{ artifactory_home }}/artifactory"
        state: link

    - name: Ensure Artifactory user owns the Artifactory directory
      file:
        path: "{{ artifactory_home }}/artifactory"
        state: directory
        owner: artifactory
        group: artifactory
        recurse: yes

    - name: Configure Artifactory service
      template:
        src: artifactory.service.j2
        dest: /etc/systemd/system/artifactory.service
      notify: restart_artifactory

    - name: Enable and start Artifactory service
      systemd:
        name: artifactory
        enabled: yes
        state: started

    # - name: Open Artifactory port in firewall
    #   firewalld:
    #     port: "{{ artifactory_port }}/tcp"
    #     state: enabled
    #     permanent: yes
    #   notify: reload_firewalld

  handlers:
    - name: restart_artifactory
      systemd:
        name: artifactory
        state: restarted
    # - name: reload_firewalld
    #   command: firewall-cmd --reload